import '../../styles/chatting/ChatList.css';
import ScrollContainer from 'react-indiana-drag-scroll';

export default function ChatList(props) {
  return (
    <>
      <ScrollContainer className="chat__list" hideScrollbars={false}>
        <ul>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
          <li>방목록</li>
        </ul>
      </ScrollContainer>
    </>
  );
}
